[package]
name = "glua"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
mlua = { version = "0.8.8", features = ["luajit"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
