[package]
name = "glua"
version = "0.0.1"
edition = "2021"

[dependencies]
bincode = "1.3.3"
daemonize = "0.5.0"
serde = { version = "1.0.162", features = ["derive"] }
mlua = { version = "0.8.8", features = ["luajit"] }
