#!/usr/bin/env bash

themes=( "gruv-light" "rose-pine-moon" "rose-pine-dawn" "rose-pine" "kanagawa" "lotus")

choices=""
for theme in "${themes[@]}"; do
  choices+="$theme\n"
done

selected_theme=$(printf "$choices" | fzf)

[[ -z $selected_theme ]] && exit 0

kakoune="$HOME/.config/kak/kakrc"
ala_path="$HOME/.config/alacritty"
ala="$ala_path/alacritty.yml"

for s in $(kak -l); do
	printf %s "colorscheme $selected_theme" | kak -p "$s"
done

[[ -f "$ala" ]] && sed -i "s#- /.*#- $ala_path/$selected_theme.yml#" "$ala"

[[ -f "$kakoune" ]] && sed -i "s/^colorscheme.*/colorscheme $selected_theme/" "$kakoune"

