#!/bin/env bash

M=( "wezterm" "fish" "i3" "i3status" "kak" )
M+=( "HoneyBunny" "Downloads" )
M+=( "$HOME/.local/scr" )

is_personal() {
	if [[ $1 =~ [[:upper:]] ]]; then
		return 0
	fi
	return 1
}

kak_connect() {
    kak -clear
    local server_name
    server_name=$(basename $PWD)
    if [[ -z $(kak -l | grep "$server_name") ]]; then
        setsid kak -d -s "$server_name" &
        sleep 0.05
    fi
    kak -c "$server_name"
}

open_editor() {
    if [[ -z $1 ]]; then
        exit 0
    fi
    test -d "$1"; builtin cd "$1" || return
    if [[ "$EDITOR" == 'kak' ]]; then
        kak_connect
    else
     	$EDITOR
	fi
}

dirs=""
for m in "${M[@]}"; do
	if is_personal "$m"; then
		dirs+="$HOME/$m "
	elif [[ $m == *"/"* ]]; then
		dirs+=$m
	else
		dirs+="$HOME/.config/$m "
	fi
done

selected_dir=$(find $dirs -maxdepth 1 -type d | fzf)
open_editor "$selected_dir"
