#!/usr/bin/env bash

dirs="$HOME/.local/scr "
dirs+="$HOME/.config "
dirs+="$HOME/Downloads "
dirs+="$HOME/HoneyBunny "
dirs+="$HOME/Nya "

spawn_editor() {
    if [ "$EDITOR" == "kak" ] && command -v kak > /dev/null; then
        local session_name=$(basename "$1" | tr ".[:space:]" "_")
        local socket_name=$(kak -l | grep -w "$session_name")

        if [ -z "$socket_name" ]; then
            setsid kak -d -s "$session_name" &
            sleep 0.05
        fi

        kak -e 'try %{cd src/}' -c "$session_name"
    else
        "$EDITOR"
    fi
}

if [[ -n "$1" && "${1,,}" != "d" ]]; then
    builtin cd "$1"
    spawn_editor "$1"
    exit 0
fi

selected=$(find $dirs -maxdepth 1 -type d | fzf)
[ -z "$selected" ] && exit 0

builtin cd "$selected"
[ "${1,,}" == "d" ] && "$SHELL" && exit 0
spawn_editor "$selected"
