#!/bin/env bash

dirs="$HOME/.local/scr "
dirs+="$HOME/.config "
dirs+="$HOME/Downloads "
dirs+="$HOME/HoneyBunny "

selected=$(find $dirs -maxdepth 1 -type d | fzy -l 100)

if [[ -z "$selected" ]]; then
    exit 0
fi

builtin cd "$selected" || return
[[ -n "$1" ]] && "$SHELL" && exit 0

if [[ "$EDITOR" == *"kak"* ]]; then
    session_name=$(basename "$selected" | tr "." "_")
    socket_name=$(kak -l | grep "$session_name")

    if [[ -z "$socket_name" ]]; then
        setsid kak -d -s "$session_name" &
        sleep 0.05
    fi

    kak -e 'try %{cd src/}' -c "$session_name"
else
    "$EDITOR"
fi
