#!/bin/env bash

content=$(cat $HOME/.config/goto.storage | tr "\n" " ")
selected=$(find $content -maxdepth 1 -type d | fzf)

if [[ -z "$selected" ]]; then
    exit 0
fi

builtin cd "$selected" || return 

if [[ "$EDITOR" == *"kak"* ]]; then
    name=$(basename "$PWD" | tr "." "_")
    socket_name=$(kak -l | grep "$name")

    if [[ -z "$socket_name" ]]; then
        setsid kak -d -s "$name" &
        sleep 0.05
    fi

    kak -c "$name"
else
    "$EDITOR"
fi
