#!/bin/env bash

# light
themes=( "rose-pine-dawn" "Gruvbox light, soft (base16)"  )
# dark
themes+=( "rose-pine" "kanagawa (Gogh)" )

choices=""
for theme in "${themes[@]}"; do
  choices+="$theme\n"
done

selected_theme=$(printf "$choices" | fzf)

if [[ -z $selected_theme ]]; then
  exit 0
fi

color_file=$HOME/.config/wezterm/color_file.lua
cat << EOF > "$color_file"
return "$selected_theme"
EOF
